version: 2.1
jobs:
  helloworld:
    docker:
      - image: cimg/node:17.2.0 # the primary container, where your job's commands are run
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD # context / project UI env-var reference
    steps:
      - checkout # check out the code in the project directory
      - run: echo "hello world" # run the `echo` command

  print-a-message:
    docker:
      - image: cimg/base:2022.03
    parameters:
      message:
        type: string
    steps:
      - run: echo "<< parameters.message >>"

workflows:
  version: 2
  print_hello_world:
    jobs:
      - helloworld
  use_custom_variable:
    jobs:
      - print-a-message:
          message: Somestring
