version: 2.1
jobs:
  helloworld:
    docker:
      - image: cimg/node:17.2.0 # the primary container, where your job's commands are run
    steps:
      - run: echo "hello world" # run the `echo` command

  print-multiple-messages:
    docker:
      - image: cimg/base:2022.03
    parameters:
      message:
        type: string
    steps:
      - run: echo "<< parameters.message >> hello world"
      - run:
          name: Run a file
          command: |
            cd ~/project/testfolder
            bash hello_there.sh circleconfig

  failing_step_for_ssh:
    docker:
      - image: cimg/base:current-22.04
    steps:
      - run:
          name: Create Gauge docker image
          command: |
            docker build -t sometag .

workflows:
  version: 2
  print_hello_world:
    steps:
      - checkout # check out the code in the project directory
      - helloworld
  print_custom_var_and_shell:
    steps:
      - checkout
      - print-multiple-messages:
          message: Somestring
  failing_build:
    steps:
      - checkout
      - failing_step_for_ssh
